all: suma_enteros cuenta_lineas ordenar

suma_enteros: suma_enteros.c
	gcc -o suma_enteros suma_enteros.c

cuenta_lineas: cuenta_lineas.c
	gcc -o cuenta_lineas cuenta_lineas.c

ordenar: ordenar.c
	gcc -o ordenar ordenar.c

clean:
	rm suma_enteros cuenta_lineas ordenar
