all: buscaLetra tachaCaracteres tachaVocales

buscaLetra: buscaLetra.c
	gcc -o buscaLetra buscaLetra.c

tachaCaracteres: tachaCaracteres.c
	gcc -o tachaCaracteres tachaCaracteres.c

tachaVocales: tachaVocales.c
	gcc -o tachaVocales tachaVocales.c
clean:
	rm buscaLetra tachaCaracteres tachaVocales
